from sqlalchemy.schema import CreateColumn
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.ext.declarative import declarative_base

# Taken from https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-10-identity-columns
# Ensures newer syntax for Postgres sequence column
@compiles(CreateColumn, 'postgresql')
def use_identity(element, compiler, **kw):
    text = compiler.visit_create_column(element, **kw)
    text = text.replace("SERIAL", "INT GENERATED BY DEFAULT AS IDENTITY")
    return text


DBBase = declarative_base()
